pub mod attr;
pub mod commands;
pub mod connections;
pub mod error;

// Back-compat re-export so existing call sites / integration tests referring to
// `app_lib::ddb` keep resolving after the move to `commands::dynamodb`.
pub use commands::dynamodb as ddb;

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    // The WebdriverIO E2E plugins are only wired up when the app is launched by
    // the wdio embedded driver, which sets TAURI_WEBDRIVER_PORT. They register
    // their own global logger, so they must NOT coexist with tauri-plugin-log
    // (that panics with "attempted to set a logger after the logging system was
    // already initialized"). Gating both on this env keeps normal `tauri dev`
    // using tauri-plugin-log while E2E runs use the wdio plugins instead.
    let under_wdio = cfg!(debug_assertions) && std::env::var_os("TAURI_WEBDRIVER_PORT").is_some();

    #[allow(unused_mut)]
    let mut builder = tauri::Builder::default();

    // The wdio plugins are desktop-only (their published crates cannot compile
    // for mobile); iOS E2E drives the webview through Appium/XCUITest instead.
    #[cfg(all(debug_assertions, not(any(target_os = "ios", target_os = "android"))))]
    if under_wdio {
        // tauri-plugin-wdio-webdriver starts an embedded W3C WebDriver server so
        // macOS can be driven without an external tauri-driver / CrabNebula.
        builder = builder
            .plugin(tauri_plugin_wdio::init())
            .plugin(tauri_plugin_wdio_webdriver::init());
    }

    builder
        .plugin(tauri_plugin_dialog::init())
        .setup(move |app| {
            if cfg!(debug_assertions) && !under_wdio {
                app.handle().plugin(
                    tauri_plugin_log::Builder::default()
                        .level(log::LevelFilter::Info)
                        .build(),
                )?;
            }
            Ok(())
        })
        .invoke_handler(tauri::generate_handler![
            connections::list_connections,
            connections::save_connection,
            connections::delete_connection,
            connections::detect_connections,
            commands::dynamodb::ddb_list_tables,
            commands::dynamodb::ddb_describe_table,
            commands::dynamodb::ddb_scan,
            commands::dynamodb::ddb_query,
            commands::dynamodb::ddb_put_item,
            commands::dynamodb::ddb_delete_item,
            commands::dynamodb::ddb_create_table,
            commands::dynamodb::ddb_delete_table,
            commands::dynamodb::ddb_execute_statement,
            commands::dynamodb::ddb_list_backups,
            commands::dynamodb::ddb_create_backup,
            commands::dynamodb::ddb_delete_backup,
            commands::dynamodb::ddb_restore_backup,
            commands::sqs::sqs_list_queues,
            commands::sqs::sqs_get_queue,
            commands::sqs::sqs_create_queue,
            commands::sqs::sqs_delete_queue,
            commands::sqs::sqs_set_queue_attributes,
            commands::sqs::sqs_send_message,
            commands::sqs::sqs_receive_messages,
            commands::sqs::sqs_delete_message,
            commands::sqs::sqs_purge_queue,
            commands::sqs::sqs_list_queue_tags,
            commands::sqs::sqs_tag_queue,
            commands::sqs::sqs_untag_queue,
            commands::sqs::sqs_list_dlq_sources,
            commands::sns::sns_list_topics,
            commands::sns::sns_create_topic,
            commands::sns::sns_delete_topic,
            commands::sns::sns_list_subscriptions,
            commands::sns::sns_subscribe_sqs,
            commands::sns::sns_unsubscribe,
            commands::sns::sns_publish,
            commands::sns::sns_get_topic_attributes,
            commands::sns::sns_set_display_name,
            commands::sns::sns_list_all_subscriptions,
            commands::sns::sns_list_topic_tags,
            commands::sns::sns_tag_topic,
            commands::sns::sns_untag_topic,
            commands::s3::s3_list_buckets,
            commands::s3::s3_create_bucket,
            commands::s3::s3_delete_bucket,
            commands::s3::s3_list_objects,
            commands::s3::s3_head_object,
            commands::s3::s3_put_object,
            commands::s3::s3_download_object,
            commands::s3::s3_delete_object,
            commands::s3::s3_get_bucket_properties,
            commands::s3::s3_set_versioning,
            commands::s3::s3_put_bucket_tagging,
            commands::s3::s3_put_bucket_cors,
            commands::s3::s3_put_bucket_policy,
            commands::s3::s3_list_object_versions,
            commands::s3::s3_download_object_version,
            commands::s3::s3_copy_object,
            commands::s3::s3_create_folder,
            commands::s3::s3_upload_file,
            commands::rds::rds_list_instances,
            commands::rds::rds_create_instance,
            commands::rds::rds_delete_instance,
            commands::rds::rds_stop_instance,
            commands::rds::rds_start_instance,
            commands::rds::rds_reboot_instance,
            commands::rds::rds_modify_instance,
            commands::rds::rds_list_snapshots,
            commands::rds::rds_create_snapshot,
            commands::rds::rds_restore_snapshot,
            commands::rds::rds_delete_snapshot,
            commands::rds::rds_list_parameter_groups,
            commands::rds::rds_create_parameter_group,
            commands::rds::rds_delete_parameter_group,
            commands::rds::rds_list_parameters,
            commands::lambda::lambda_list_functions,
            commands::lambda::lambda_get_function,
            commands::lambda::lambda_create_function,
            commands::lambda::lambda_update_function_code,
            commands::lambda::lambda_update_function_config,
            commands::lambda::lambda_delete_function,
            commands::lambda::lambda_invoke,
            commands::lambda::lambda_list_layers,
            commands::lambda::lambda_publish_layer_version,
            commands::lambda::lambda_delete_layer_version,
            commands::apigateway::apigw_list_apis,
            commands::apigateway::apigw_create_api,
            commands::apigateway::apigw_delete_api,
            commands::apigateway::apigw_get_resources,
            commands::apigateway::apigw_create_resource,
            commands::apigateway::apigw_put_method,
            commands::apigateway::apigw_create_deployment,
            commands::apigateway::apigw_list_stages,
            commands::apigateway::apigw_list_api_keys,
            commands::apigateway::apigw_create_api_key,
            commands::apigateway::apigw_delete_api_key,
            commands::cognito::cognito_list_user_pools,
            commands::cognito::cognito_create_user_pool,
            commands::cognito::cognito_delete_user_pool,
            commands::cognito::cognito_get_user_pool,
            commands::cognito::cognito_list_users,
            commands::cognito::cognito_admin_create_user,
            commands::cognito::cognito_admin_set_user_password,
            commands::cognito::cognito_admin_enable_user,
            commands::cognito::cognito_admin_disable_user,
            commands::cognito::cognito_admin_delete_user,
            commands::cognito::cognito_list_user_pool_clients,
            commands::cognito::cognito_create_user_pool_client,
            commands::cognito::cognito_delete_user_pool_client,
            commands::cognito::cognito_list_groups,
            commands::cognito::cognito_create_group,
            commands::cognito::cognito_delete_group,
            commands::eventbridge::events_list_buses,
            commands::eventbridge::events_create_bus,
            commands::eventbridge::events_delete_bus,
            commands::eventbridge::events_list_rules,
            commands::eventbridge::events_put_rule,
            commands::eventbridge::events_delete_rule,
            commands::eventbridge::events_enable_rule,
            commands::eventbridge::events_disable_rule,
            commands::eventbridge::events_list_targets,
            commands::eventbridge::events_put_target,
            commands::eventbridge::events_remove_target,
            commands::eventbridge::events_put_events,
            commands::secretsmanager::secrets_list,
            commands::secretsmanager::secrets_create,
            commands::secretsmanager::secrets_describe,
            commands::secretsmanager::secrets_get_value,
            commands::secretsmanager::secrets_put_value,
            commands::secretsmanager::secrets_list_versions,
            commands::secretsmanager::secrets_delete,
            commands::secretsmanager::secrets_tag,
            commands::secretsmanager::secrets_untag,
            commands::elasticache::elasticache_list_caches,
            commands::elasticache::elasticache_create_cache,
            commands::elasticache::elasticache_delete_cache,
            commands::elasticache::elasticache_get_cache,
            commands::cloudformation::cfn_list_stacks,
            commands::cloudformation::cfn_create_stack,
            commands::cloudformation::cfn_update_stack,
            commands::cloudformation::cfn_delete_stack,
            commands::cloudformation::cfn_get_stack,
            commands::cloudformation::cfn_list_resources,
            commands::cloudformation::cfn_list_events,
            commands::cloudformation::cfn_get_template,
            commands::cloudformation::cfn_list_exports,
            commands::ecs::ecs_list_clusters,
            commands::ecs::ecs_create_cluster,
            commands::ecs::ecs_delete_cluster,
            commands::ecs::ecs_list_task_definitions,
            commands::ecs::ecs_register_task_definition,
            commands::ecs::ecs_describe_task_definition,
            commands::ecs::ecs_deregister_task_definition,
            commands::ecs::ecs_list_services,
            commands::ecs::ecs_create_service,
            commands::ecs::ecs_update_service,
            commands::ecs::ecs_delete_service,
            commands::ecs::ecs_list_tasks,
            commands::ecs::ecs_run_task,
            commands::ecs::ecs_stop_task,
            commands::ecr::ecr_list_repositories,
            commands::ecr::ecr_create_repository,
            commands::ecr::ecr_delete_repository,
            commands::ecr::ecr_list_images,
            commands::cloudwatch::cw_list_log_groups,
            commands::cloudwatch::cw_create_log_group,
            commands::cloudwatch::cw_delete_log_group,
            commands::cloudwatch::cw_list_log_streams,
            commands::cloudwatch::cw_get_log_events,
            commands::cloudwatch::cw_filter_log_events,
            commands::cloudwatch_query::cw_list_metrics,
            commands::cloudwatch_query::cw_get_metric_statistics,
            commands::cloudwatch_query::cw_describe_alarms,
            commands::cloudwatch_query::cw_put_metric_alarm,
            commands::cloudwatch_query::cw_delete_alarms,
            commands::stepfunctions::sfn_list_state_machines,
            commands::stepfunctions::sfn_create_state_machine,
            commands::stepfunctions::sfn_update_state_machine,
            commands::stepfunctions::sfn_delete_state_machine,
            commands::stepfunctions::sfn_describe_state_machine,
            commands::stepfunctions::sfn_start_execution,
            commands::stepfunctions::sfn_list_executions,
            commands::stepfunctions::sfn_describe_execution,
            commands::stepfunctions::sfn_get_execution_history,
            commands::opensearch::opensearch_list_domains,
            commands::opensearch::opensearch_create_domain,
            commands::opensearch::opensearch_delete_domain,
            commands::opensearch::opensearch_get_domain,
            commands::athena::athena_start_query,
            commands::athena::athena_get_query_execution,
            commands::athena::athena_get_query_results,
            commands::athena::athena_list_workgroups,
            commands::athena::athena_create_workgroup,
            commands::athena::athena_delete_workgroup,
            commands::athena::athena_list_named_queries,
            commands::athena::athena_create_named_query,
            commands::athena::athena_delete_named_query,
            commands::msk::msk_list_clusters,
            commands::msk::msk_create_cluster,
            commands::msk::msk_delete_cluster,
            commands::msk::msk_describe_cluster,
            commands::msk::msk_get_bootstrap_brokers,
            commands::ssm::ssm_list_parameters,
            commands::ssm::ssm_get_parameter,
            commands::ssm::ssm_put_parameter,
            commands::ssm::ssm_delete_parameter,
            commands::ssm::ssm_get_parameter_history,
            commands::route53::route53_list_hosted_zones,
            commands::route53::route53_create_hosted_zone,
            commands::route53::route53_delete_hosted_zone,
            commands::route53::route53_list_record_sets,
            commands::route53::route53_change_record_set,
            commands::route53::route53_list_health_checks,
            commands::route53::route53_create_health_check,
            commands::route53::route53_delete_health_check,
        ])
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
